from . import (
    apimodule,
    appmodule,
    djangoapp,
    djangoapp_and_module,
    djangoapp_and_postgres,
    djangoapp_and_service,
    form,
    graphene_django,
    graphql_auth,
    item,
    itemlist,
    itemtype,
    module,
    postgresservice,
    strapi,
    strapidockerimage,
)

modules = [
    apimodule,
    appmodule,
    djangoapp_and_postgres,
    djangoapp_and_module,
    djangoapp_and_service,
    form,
    djangoapp,
    graphene_django,
    graphql_auth,
    item,
    itemlist,
    itemtype,
    module,
    postgresservice,
    strapi,
    strapidockerimage,
]
