{% trim_newlines keep=1 %}
FROM {{ res.image_name }}

{{ res.custom_steps_pre }}

                                                            {% for PKG in res.service.get_pkg_names("prod") %}
# install pkg dependencies                                  {% if loop.first %}
RUN {{ res.docker_image.install_command }} \                {% endif %}
    {{ PKG }} \                                             {% if not loop.last %}
    {{ PKG }}                                               {% else %}{% endif %}
                                                            {% endfor %}

                                                            {% for PKG in res.service.get_pip_pkg_names("base") %}
# install pip dependencies                                  {% if loop.first %}
RUN pip install \                                           {% endif %}
    {{ PKG }} \                                             {% if not loop.last %}
    {{ PKG }}                                               {% else %}{% endif %}
                                                            {% endfor %}

{{ res.custom_steps }}

# Install requirements
RUN pip install -r /app/src/.requirements/prod.txt

WORKDIR {{ res.service.install_dir }}/src
{% end_trim_newlines %}