{% trim_newlines keep=1 %}
FROM {{ res.image_name }}

{{ res.custom_steps_pre_dev }}
                                                                                {% for PKG in res.service.get_pkg_names("prod") %}
# install pkg dependencies                                                      {% if loop.first %}
RUN {{ res.docker_image.install_command }} \                                    {% endif %}
    {{ PKG }} \                                                                 {% if not loop.last %}
    {{ PKG }}                                                                   {% else %}{% endif %}
                                                                                {% endfor %}

                                                                                {% for PKG in res.service.get_pip_pkg_names("base") %}
# install pip dependencies                                                      {% if loop.first %}
RUN {{ res.docker_image.pip }} install \                                        {% endif %}
    {{ PKG }} \                                                                 {% if not loop.last %}
    {{ PKG }}                                                                   {% else %}{% endif %}
                                                                                {% endfor %}

                                                                                {% for PKG in res.service.get_pkg_names("dev") %}
# install dev pkg dependencies                                                  {% if loop.first %}
RUN {{ res.docker_image.install_command }} \                                    {% endif %}
    {{ PKG }} \                                                                 {% if not loop.last %}
    {{ PKG }}                                                                   {% else %}{% endif %}
                                                                                {% endfor %}

                                                                                {% for PKG in res.service.get_pip_pkg_names("dev") %}
# install dev pip dependencies                                                  {% if loop.first %}
RUN {{ res.docker_image.pip }} install \                                        {% endif %}
    {{ PKG }} \                                                                 {% if not loop.last %}
    {{ PKG }}                                                                   {% else %}{% endif %}
                                                                                {% endfor %}

{{ res.custom_steps_dev }}

WORKDIR {{ res.service.install_dir }}/src
{% end_trim_newlines %}
