configured_by = ("configured",)
uses = ("use", "uses")
contains = ("has", "have", "contain", "contains")
stores = ("stores",)
has = contains + uses
is_created_as = "is-created-as"
runs = ("run", "runs", "running")
connects = ("connects",)
loads = ("loads",)
saves = ("saves",)
deletes = ("deletes",)
supports = ("supports",)
provides = ("provides",)
