{% trim_newlines keep=1 %}
FROM {{ __.dockerfile.image_name }}

RUN {{ _.service.pip }} install --upgrade pip                                                   {% ?? _.service.pip %}

# install pkg dependencies
RUN {{ __.docker_image.install_command }} \
    make

{% min_lines count=3 %}
# install dev pkg dependencies
RUN {{ __.docker_image.install_command }} \
    fish \                                                                                      {% ?? _.service.fish %}
    nano \
    postgresql-client \                                                                         {% ?? _.service.is_dependent_on("postgres") %}
    {% remove_trailing suffix="__backslash__" %}
{% end_min_lines %}

{% min_lines count=3 %}
{% if _.service.pip %}
# install dev pip dependencies
RUN {{ _.service.pip }} install \
    pgcli==3.4.1                                                                                {% ?? _.service.is_dependent_on("postgres") %}
{% endif %}
{% end_min_lines %}

# Prevent any problems with stale .pyc files preventing the use of the latest .py files         {% if _.service.pip %}
ENV PYTHONDONTWRITEBYTECODE 1

# Ensure that no messages are still in the buffer (and never printed) in case of a crash
ENV PYTHONUNBUFFERED 1
                                                                                                {% endif %}
# Copy source files                                                                             {% if _.service.copy_source_to_prod_image %}
RUN mkdir -p {{ _.service.install_dir }}/src
COPY . {{ _.service.install_dir }}/src                                                          {% endif %}

# Install requirements                                                                          {% if _.service.pip %}
RUN {{ _.service.pip }} install -r {{ _.service.install_dir }}/src/.requirements/prod.txt       {% endif %}

WORKDIR {{ _.service.install_dir }}/src

CMD make --file=Makefile.prod start-prod
{% end_trim_newlines %}
