from . import (
    accountsmodule,
    apimodule,
    appmodule,
    djangoapp,
    djangoapp_and_module,
    djangoapp_and_postgres,
    djangoapp_and_service,
    djangomodel,
    extendspectypes,
    graphene_django,
    graphql_auth,
    module,
    usersmodule,
)

modules = [
    accountsmodule,
    apimodule,
    appmodule,
    djangoapp_and_postgres,
    djangoapp_and_module,
    djangoapp_and_service,
    djangomodel,
    extendspectypes,
    djangoapp,
    graphene_django,
    graphql_auth,
    module,
    usersmodule,
]
