FROM {{ res.image.name }}

# install pkg dependencies
{% for pkg in res.service.pkg_dependencies %}
RUN {{ res.install_command }} \
{% body %}
    {{ pkg + (' \\' if not loop.last else '') }}

# install pip dependencies
{% for pkg in res.service.pip_dependencies %}
RUN pip install \
{% body %}
    {{ pkg + (' \\' if not loop.last else '') }}

# install dev pkg dependencies
{% for pkg in res.service.pkg_dependencies_dev %}
RUN {{ res.install_command }} \
{% body %}
    {{ pkg + (' \\' if not loop.last else '') }}

# install dev pip dependencies
{% for pkg in res.service.pip_dependencies_dev %}
RUN pip install \
{% body %}
    {{ pkg + (' \\' if not loop.last else '') }}
