FROM foodev

{% for pkg in res.service.pkg_dependencies_dev|sum(attribute="package_name", start = []) %}
{% if loop.first %}
RUN {{ res.install_command }} \
{% endif %}
    {{ pkg + ' \\' if not loop.last else pkg }}
{% endfor %}

{% for pip_pkg in res.service.pip_dependencies_dev %}
RUN pip install {{ pip_pkg.package_name }}
{% endfor %}