{% trim_newlines keep=1 %}
FROM {{ __.dockerfile.image_name }}

RUN {{ _.service.pip }} install --upgrade pip                                   {% ?? _.service.pip %}

# Add ppa for postgresql-client-14                                              {% if _.service.is_dependent_on("postgres") %}
RUN apt policy postgresql
RUN curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

                                                                                {% endif %}
# install pkg dependencies
RUN {{ __.docker_image.install_command }} \
    make

# install dev pkg dependencies                                                  {% min_lines count=3 %}
RUN {{ __.docker_image.install_command }} \
    curl \
    fish \                                                                      {% ?? _.service.fish %}
    nano \
    postgresql-client-14 \                                                      {% ?? _.service.is_dependent_on("postgres") %}
    {% remove_trailing suffix="__backslash__" %}                                {% end_min_lines %}

# create a python venv that we can easily store inside a docker volume          {% if _.service.pip %}
RUN python3 -m venv {{ _.service.install_dir }}/env
ENV PATH="{{ _.service.install_dir }}/env/bin:${PATH}"

# install dev pip dependencies                                                  {% min_lines count=3 %}
RUN {{ _.service.pip }} install \
    black \                                                                     {% ?? _.service.black %}
    ipython \                                                                   {% ?? _.service.pudb %}
    isort \                                                                     {% ?? _.service.isort %}
    pgcli==3.4.1 \                                                              {% ?? _.service.is_dependent_on("postgres") %}
    pip-tools \                                                                 {% ?? _.service.pip_compile %}
    pudb \                                                                      {% ?? _.service.pudb %}
    {% remove_trailing suffix="__backslash__" %}                                {% end_min_lines %}
                                                                                {% endif %}

WORKDIR {{ __.dockerfile.service.install_dir }}/src
{% end_trim_newlines %}
