{% trim_newlines keep=1 %}

{% include_snippet '__moonleap__/Makefile.postgres.j2' %}
{% include_snippet '__moonleap__/Makefile.pip.j2' %}
{% include_snippet '__moonleap__/Makefile.django.j2' %}
{% include_snippet '__moonleap__/Makefile.react.j2' %}

#
# Stack
#

init-dev: \
	create-db \            															{% ?? _.service.has_django_app %}
	pip-compile \																	{% ?? _.service.pip %}
	install \
	make-migrations-users \                         								{% ?? _.service.has_django_app and _.service.django_app.get_module_by_name("users") %}
	migrate \            															{% ?? _.service.has_django_app %}
	collect-static \       															{% ?? _.service.has_django_app %}
	create-superuser \  															{% ?? _.service.has_django_app %}
	{% remove_trailing suffix="__backslash__" %}

{% end_trim_newlines %}