FROM {{ res.image_name }}

# install pkg dependencies
{% for pkg in res.service.get_pkg_names() %}
RUN {{ res.install_command }} \
{% body %}
    {{ pkg + (' \\' if not loop.last else '') }}

# install pip dependencies
{% for pkg in res.service.get_pip_pkg_names() %}
RUN pip install \
{% body %}
    {{ pkg + (' \\' if not loop.last else '') }}

# install dev pkg dependencies
{% for pkg in res.service.get_pkg_names(is_dev=True) %}
RUN {{ res.install_command }} \
{% body %}
    {{ pkg + (' \\' if not loop.last else '') }}

# install dev pip dependencies
{% for pkg in res.service.get_pip_pkg_names(is_dev=True) %}
RUN pip install \
{% body %}
    {{ pkg + (' \\' if not loop.last else '') }}

WORKDIR /app/src