{% trim_newlines keep=1 %}
FROM {{ res.image_name }}

{% for PKG in res.service.get_pkg_names() %}{% if loop.first %}
# install pkg dependencies
RUN {{ res.docker_image.install_command }} \
{% endif %}{% if not loop.last %}
    {{ PKG }} \
{% else %}
    {{ PKG }}
{% endif %}{% endfor %}

{% for PKG in res.service.get_pip_pkg_names() %}{% if loop.first %}
# install pip dependencies
RUN pip install \
{% endif %}{% if not loop.last %}
    {{ PKG }} \
{% else %}
    {{ PKG }}
{% endif %}{% endfor %}

WORKDIR {{ res.service.install_dir }}/src
{% end_trim_newlines %}