FROM {{ res.image_name }}

# install pkg dependencies
RUN {{ res.install_command }} \
{% loop PKG in res.service.get_pkg_names() %}
    {{ PKG }} \
{% endloop %}
    {{ PKG }}

# install pip dependencies
RUN pip install \
{% loop PKG in res.service.get_pip_pkg_names() %}
    {{ PKG }} \
{% endloop %}
    {{ PKG }}

WORKDIR /app/src