ROOT_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

init-dev:
	pip install compile-env==0.4.1

compile-env:
	cd ${ROOT_DIR}/env/dev && compile-env env-spec.yaml

create-opt-paths:
{% for service in _.project.services %}
	sudo mkdir -p /opt/{{ _.project.name }}/{{ service.name }}/fish_history                   {% ?? service.fish %}
	sudo mkdir -p /opt/{{ _.project.name }}/{{ service.name }}/ipython                        {% ?? service.pudb %}
	sudo mkdir -p /opt/{{ _.project.name }}/{{ service.name }}/assets                         {% ?? service.pytest %}
	sudo touch    /opt/{{ _.project.name }}/{{ service.name }}/pytest_report.html             {% ?? service.pytest %}
	sudo mkdir -p /opt/{{ _.project.name }}/{{ service.name }}/media                          {% ?? service.has_django_app %}
	sudo mkdir -p /opt/{{ _.project.name }}/{{ service.name }}/static                         {% ?? service.has_django_app %}
{% endfor %}