from . import (
    authmodule,
    component,
    cypress,
    module,
    module_and_component,
    nodepackage,
    pkg,
    prettier,
    reactapp,
    reactapp_and_module,
    reactapp_and_service,
    router,
    router_and_module,
    tailwindcss,
    uikit,
    utilsmodule,
)

modules = [
    authmodule,
    component,
    cypress,
    pkg,
    module_and_component,
    module,
    nodepackage,
    prettier,
    reactapp,
    reactapp_and_module,
    reactapp_and_service,
    router_and_module,
    router,
    tailwindcss,
    uikit,
    utilsmodule,
]
