from . import (
    apimodule,
    appmodule,
    appstore,
    flags,
    graphqlapi,
    item,
    itemlist,
    itemtype,
    loaditemeffect,
    loaditemseffect,
    mockgraphqlserver,
    policy,
    store,
    storeprovider,
    utilsmodule,
)

modules = [
    (apimodule),
    (appmodule),
    (appstore),
    (flags),
    (graphqlapi),
    (item),
    (itemlist),
    (itemtype),
    (loaditemeffect),
    (loaditemseffect),
    (mockgraphqlserver),
    (policy),
    (store),
    (storeprovider),
    (utilsmodule),
]
